import Head from 'next/head';
import Header from './Header';

const Layout = ({
	children,
	tw,
}: {
	children: React.ReactNode;
	tw?: string;
}) => {
	return (
		<>
			<Head>
				<title>Next Auth</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={`${tw}`}>
				<Header />
				<main className='center min-h-screen px-8 -mt-28'>{children}</main>
			</div>
		</>
	);
};

export default Layout;
